[package]
name = "bindlesstexture"
description = "Support for bindless textures in Vulkan"
version = "0.1.0"
authors = ["John Nagle <nagle@animats.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
#   Rendering-related
env_logger = "0.10.1"
